a = float(input('give me first numb : '))
b = float(input('give me second numb : '))
c = float(input('give me third numb : '))
x1 = (-b+(b**2 - 4*a*c)**0.5)/(2*a)
x2 = (-b-(b**2 - 4*a*c)**0.5)/(2*a)
print(f'x1:{x1},x2{x2}')
